export const TooltipText = {
  AddFile: 'Add a new file',
  RenameFile: 'Rename',
  DeleteFile: 'Delete',
  isEntry: 'Entry File',
  SetEntry: 'Set to entry',
  ToggleFiles: (show: boolean) => `${show ? 'Hide' : 'Show'} FileBar`,
  ToggleCode: (show: boolean) => `${show ? 'Hide' : 'Show'} Code Editor`,
  Settings: 'Settings',
  ToggleWebPreview: (show: boolean) => `${show ? 'Hide' : 'Show'} Web Preview`,
  RefreshWebPreview: 'Refresh Web Preview',
  SwapLayout: 'Swap the position of CodeEditor and WebPreview',
  CopyCode: 'Copy code to clipboard',
  Share: 'Share the page',
};
