export declare const COMP_IDENTIFIER = "__sfc__";
export declare const modulesKey = "__modules__";
export declare const exportKey = "__export__";
export declare const dynamicImportKey = "__dynamic_import__";
export declare const moduleKey = "__module__";
export declare const nextKey = "__next__";
export declare const scriptRE: RegExp;
export declare const scriptModuleRE: RegExp;
export declare const MapFile = "import-map.json";
export declare const version = "3.2.45";
export declare const defaultMainFile = "App.vue";
export declare const fileTypes: string[];
export declare const URLCodeKey = "_codesandbox_code";
export * from './tooltip';
